import mongoose from "mongoose";

const challengeSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    required: true,
    trim: true,
  },
  icon: {
    type: String,
    required: true,
    trim: true,
  },
  type: {
    type: String,
    required: true,
    enum: ["spending_limit", "category_ban", "streak_target", "savings_target", "logging_target", "custom"],
  },
  config: {
    category: { type: String, default: null },
    targetAmount: { type: Number, default: 0 },
    targetDays: { type: Number, default: 0 },
    targetSavings: { type: Number, default: 0 },
    comparisonType: { type: String, enum: ["absolute", "percentage_reduction", null], default: null },
    weekendsOnly: { type: Boolean, default: false },
  },
  duration: {
    type: String,
    required: true,
    enum: ["1_week", "2_weeks", "1_month"],
  },
  startDate: {
    type: Date,
    required: true,
  },
  endDate: {
    type: Date,
    required: true,
  },
  badgeReward: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Badge",
    default: null,
  },
  xpReward: {
    type: Number,
    required: true,
    default: 0,
  },
  isGlobal: {
    type: Boolean,
    default: true,
  },
  isAutoGenerated: {
    type: Boolean,
    default: false,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

challengeSchema.index({ startDate: 1, endDate: 1 });
challengeSchema.index({ isGlobal: 1, endDate: 1 });

const Challenge = mongoose.model("Challenge", challengeSchema);
export default Challenge;
