import Challenge from "../models/Challenge.js";
import UserChallenge from "../models/UserChallenge.js";
import Transaction from "../models/Transaction.js";
import User from "../models/User.js";
import { awardXP } from "./xpService.js";

// ─── Challenge Templates ────────────────────────────────────────────────────
const CHALLENGE_TEMPLATES = [
  {
    title: "No Outside Food Week",
    description: "Avoid spending on restaurants and takeout for 7 days",
    icon: "🍳",
    type: "category_ban",
    config: { category: "Food", targetDays: 7 },
    duration: "1_week",
    xpReward: 75,
  },
  {
    title: "₹500/day Challenge",
    description: "Keep daily spending under ₹500 for a week",
    icon: "💪",
    type: "spending_limit",
    config: { targetAmount: 500, targetDays: 7 },
    duration: "1_week",
    xpReward: 100,
  },
  {
    title: "Streak Builder",
    description: "Log expenses every single day for 14 days",
    icon: "🔥",
    type: "logging_target",
    config: { targetDays: 14 },
    duration: "2_weeks",
    xpReward: 120,
  },
  {
    title: "Monthly Saver",
    description: "Save at least ₹5,000 this month",
    icon: "🏦",
    type: "savings_target",
    config: { targetSavings: 5000 },
    duration: "1_month",
    xpReward: 200,
  },
  {
    title: "Budget Master",
    description: "Stay under daily budget for 21 days in a month",
    icon: "🎯",
    type: "streak_target",
    config: { targetDays: 21 },
    duration: "1_month",
    xpReward: 180,
  },
  {
    title: "Weekend Warrior",
    description: "No spending on weekends for 2 weeks",
    icon: "🛡️",
    type: "spending_limit",
    config: { targetAmount: 0, targetDays: 4, weekendsOnly: true },
    duration: "2_weeks",
    xpReward: 150,
  },
  {
    title: "Entertainment Diet",
    description: "Zero entertainment spending for 2 weeks",
    icon: "🎮",
    type: "category_ban",
    config: { category: "Entertainment", targetDays: 14 },
    duration: "2_weeks",
    xpReward: 100,
  },
  {
    title: "Receipt Scanner Pro",
    description: "Scan at least 10 receipts this month",
    icon: "📸",
    type: "custom",
    config: { targetAmount: 10 },
    duration: "1_month",
    xpReward: 80,
  },
];

/**
 * Generate challenges for a new month.
 * Picks 3-4 random templates and creates Challenge documents.
 */
export const generateMonthlyChallenges = async () => {
  const now = new Date();
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const monthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

  // Check if challenges already exist for this month
  const existing = await Challenge.countDocuments({
    isAutoGenerated: true,
    startDate: { $gte: monthStart },
  });

  if (existing > 0) return { message: "Challenges already generated for this month", count: existing };

  // Pick 4 random templates
  const shuffled = [...CHALLENGE_TEMPLATES].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, 4);

  const created = [];
  for (const template of selected) {
    let startDate = monthStart;
    let endDate = monthEnd;

    if (template.duration === "1_week") {
      endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + 7);
    } else if (template.duration === "2_weeks") {
      endDate = new Date(startDate);
      endDate.setDate(endDate.getDate() + 14);
    }

    const challenge = await Challenge.create({
      ...template,
      startDate,
      endDate,
      isGlobal: true,
      isAutoGenerated: true,
    });

    created.push(challenge);
  }

  console.log(`🎮 [Challenge Service] Generated ${created.length} monthly challenges`);
  return { message: "Monthly challenges generated", count: created.length, challenges: created };
};

/**
 * Get active challenges for display (user can join any).
 */
export const getActiveChallenges = async (userId) => {
  const now = new Date();

  // Get all active global challenges
  const challenges = await Challenge.find({
    isGlobal: true,
    endDate: { $gte: now },
  })
    .sort({ startDate: -1 })
    .lean();

  // Get user's joined challenges
  const userChallenges = await UserChallenge.find({
    user: userId,
    challenge: { $in: challenges.map((c) => c._id) },
  }).lean();

  const joinedMap = new Map();
  for (const uc of userChallenges) {
    joinedMap.set(uc.challenge.toString(), uc);
  }

  return challenges.map((challenge) => {
    const userChallenge = joinedMap.get(challenge._id.toString());
    return {
      ...challenge,
      joined: !!userChallenge,
      userProgress: userChallenge
        ? {
            current: userChallenge.progress.current,
            target: userChallenge.progress.target,
            percentage: userChallenge.progress.percentage,
            status: userChallenge.status,
          }
        : null,
    };
  });
};

/**
 * Get active challenges the current user has joined.
 */
export const getMyActiveChallenges = async (userId) => {
  const now = new Date();
  const userChallenges = await UserChallenge.find({
    user: userId,
    status: "active",
  })
    .populate({
      path: "challenge",
      match: { endDate: { $gte: now } },
    })
    .sort({ createdAt: -1 })
    .lean();

  return userChallenges
    .filter((userChallenge) => userChallenge.challenge)
    .map((userChallenge) => ({
      ...userChallenge.challenge,
      joined: true,
      userProgress: {
        current: userChallenge.progress.current,
        target: userChallenge.progress.target,
        percentage: userChallenge.progress.percentage,
        status: userChallenge.status,
      },
      joinedAt: userChallenge.joinedAt,
    }));
};

/**
 * Join a challenge.
 */
export const joinChallenge = async (userId, challengeId) => {
  const challenge = await Challenge.findById(challengeId);
  if (!challenge) throw new Error("Challenge not found");

  // Check not already joined
  const existing = await UserChallenge.findOne({ user: userId, challenge: challengeId });
  if (existing) throw new Error("Already joined this challenge");

  // Calculate target based on challenge type
  let target = challenge.config.targetDays || challenge.config.targetAmount || challenge.config.targetSavings || 1;

  const userChallenge = await UserChallenge.create({
    user: userId,
    challenge: challengeId,
    progress: {
      current: 0,
      target,
      percentage: 0,
      dailyLog: [],
    },
    status: "active",
  });

  // Award XP for joining
  await awardXP(userId, "challenge_joined");

  return userChallenge;
};

/**
 * Update challenge progress for a user (called daily or on action).
 */
export const updateChallengeProgress = async (userId) => {
  const activeChallenges = await UserChallenge.find({
    user: userId,
    status: "active",
  }).populate("challenge");

  const results = [];
  const now = new Date();
  const todayStart = new Date(now);
  todayStart.setHours(0, 0, 0, 0);
  const todayEnd = new Date(now);
  todayEnd.setHours(23, 59, 59, 999);

  for (const uc of activeChallenges) {
    const challenge = uc.challenge;
    if (!challenge) continue;

    // Check if challenge has expired
    if (now > new Date(challenge.endDate)) {
      uc.status = uc.progress.percentage >= 100 ? "completed" : "failed";
      if (uc.status === "completed") {
        uc.completedAt = now;
        uc.xpAwarded = challenge.xpReward;
        await awardXP(userId, "goal_completed"); // reuse XP key
      }
      await uc.save();
      results.push({ challengeId: challenge._id, status: uc.status });
      continue;
    }

    let todayValue = 0;
    let passed = false;

    switch (challenge.type) {
      case "spending_limit": {
        const todaySpent = await Transaction.aggregate([
          { $match: { user: uc.user, type: "expense", date: { $gte: todayStart, $lte: todayEnd } } },
          { $group: { _id: null, total: { $sum: "$amount" } } },
        ]);
        todayValue = todaySpent[0]?.total || 0;
        passed = todayValue <= (challenge.config.targetAmount || 0);
        break;
      }

      case "category_ban": {
        const catSpend = await Transaction.countDocuments({
          user: uc.user,
          type: "expense",
          category: challenge.config.category,
          date: { $gte: todayStart, $lte: todayEnd },
        });
        todayValue = catSpend;
        passed = catSpend === 0;
        break;
      }

      case "logging_target": {
        const logged = await Transaction.countDocuments({
          user: uc.user,
          date: { $gte: todayStart, $lte: todayEnd },
        });
        todayValue = logged;
        passed = logged > 0;
        break;
      }

      case "streak_target": {
        const user = await User.findById(userId).select("streaks").lean();
        todayValue = user?.streaks?.underBudget?.current || 0;
        passed = todayValue > uc.progress.current;
        break;
      }

      case "savings_target": {
        // Check total savings progress
        const { default: SavingsGoal } = await import("../models/SavingsGoal.js");
        const goals = await SavingsGoal.find({ user: userId }).select("savedAmount").lean();
        const total = goals.reduce((sum, g) => sum + (g.savedAmount || 0), 0);
        todayValue = total;
        passed = total >= (challenge.config.targetSavings || 0);
        break;
      }

      default:
        continue;
    }

    // Update daily log (avoid duplicates for same day)
    const alreadyLoggedToday = uc.progress.dailyLog.some(
      (d) => new Date(d.date).toDateString() === now.toDateString()
    );

    if (!alreadyLoggedToday) {
      uc.progress.dailyLog.push({
        date: now,
        value: todayValue,
        passed,
      });
    }

    // Recalculate progress
    const passedDays = uc.progress.dailyLog.filter((d) => d.passed).length;

    if (challenge.type === "savings_target") {
      uc.progress.current = todayValue;
      uc.progress.percentage = Math.min(100, Math.round((todayValue / uc.progress.target) * 100));
    } else {
      uc.progress.current = passedDays;
      uc.progress.percentage = Math.min(100, Math.round((passedDays / uc.progress.target) * 100));
    }

    // Check completion
    if (uc.progress.percentage >= 100 && uc.status === "active") {
      uc.status = "completed";
      uc.completedAt = now;
      uc.xpAwarded = challenge.xpReward;
      await awardXP(userId, "goal_completed");
    }

    uc.markModified("progress");
    await uc.save();

    results.push({
      challengeId: challenge._id,
      title: challenge.title,
      progress: uc.progress.percentage,
      status: uc.status,
    });
  }

  return results;
};

/**
 * Get user's challenge history.
 */
export const getUserChallengeHistory = async (userId) => {
  const challenges = await UserChallenge.find({ user: userId })
    .populate("challenge")
    .sort({ createdAt: -1 })
    .lean();

  return challenges.map((uc) => ({
    _id: uc._id,
    challenge: uc.challenge,
    status: uc.status,
    progress: uc.progress,
    joinedAt: uc.joinedAt,
    completedAt: uc.completedAt,
    xpAwarded: uc.xpAwarded,
  }));
};

/**
 * Abandon a challenge.
 */
export const abandonChallenge = async (userId, challengeId) => {
  const uc = await UserChallenge.findOne({
    user: userId,
    challenge: challengeId,
    status: "active",
  });

  if (!uc) throw new Error("Active challenge not found");

  uc.status = "abandoned";
  await uc.save();

  return { success: true, message: "Challenge abandoned" };
};
