// Cache middleware for Express routes.
//
// cacheResponse — wraps res.json() to store the response body in the in-memory cache.
//   The key is generated by the caller so different routes can encode user/month/etc.
//   Only caches successful (200 + success:true) responses to avoid storing errors.
//
// invalidateCache — wraps res.json() to clear cache entries after a successful write.
//   Patterns are prefix-based: invalidatePattern("summary:userId") clears all months for that user.

import { cache } from "../utils/cache.js";

/**
 * @param {(req: Request) => string} keyGenerator - Returns the cache key for a request.
 * @param {number} ttl - Time-to-live in seconds.
 */
export const cacheResponse = (keyGenerator, ttl = 300) => {
  return (req, res, next) => {
    const key = keyGenerator(req);
    const cached = cache.get(key);

    if (cached) {
      // Signal to the client that this response came from cache.
      res.set("X-Cache", "HIT");
      return res.status(200).json(cached);
    }

    res.set("X-Cache", "MISS");

    // Override res.json so we can intercept the outgoing body and store it.
    const originalJson = res.json.bind(res);
    res.json = (body) => {
      // Only cache successful responses — never cache errors or empty results.
      if (res.statusCode === 200 && body && body.success) {
        cache.set(key, body, ttl);
      }
      return originalJson(body);
    };

    next();
  };
};

/**
 * @param {(req: Request) => string[]} patternsGenerator - Returns an array of prefix patterns to invalidate.
 */
export const invalidateCache = (patternsGenerator) => {
  return (req, res, next) => {
    const originalJson = res.json.bind(res);
    res.json = (body) => {
      // Only invalidate when the write operation succeeded.
      if (body && body.success) {
        const patterns = patternsGenerator(req);
        patterns.forEach((pattern) => cache.invalidatePattern(pattern));
      }
      return originalJson(body);
    };

    next();
  };
};
