export const XP_AWARDS = {
  transaction_logged: 5,
  first_transaction_of_day: 10,
  streak_day: 5,
  streak_milestone_7: 30,
  streak_milestone_30: 100,
  streak_milestone_100: 500,
  under_budget_day: 10,
  under_budget_week: 50,
  under_budget_month: 200,
  savings_added: 5,
  goal_milestone_25: 25,
  goal_milestone_50: 50,
  goal_milestone_75: 75,
  goal_completed: 200,
  receipt_scanned: 10,
  challenge_joined: 5,
  family_created: 25,
  member_invited: 10,
  healthy_food_choice: 5,
  no_junk_day: 10,
  login_streak_day: 3,
  first_budget_created: 20,
  first_goal_created: 15,
  first_receipt_scan: 15,
};
